### ISSUE TITLE
Inversion for one screen

### ISSUE THREAD

**Issue by HerelAdrastel** [mlaily/NegativeScreen#14]
Hi, 

I have 2 screens. I wonder if it's possible to make the inversion color for only one screen. If it's takes too much time, can you tell me where I can edit the dimensions of the window  ? (I'll hard code and compile the program ^^)

**Comment by mlaily** [comment]
Hi!

The current version uses the fullscreen magnification api, making it impossible to control what is inverted or not. (I use the fullscreen api because it is significantly more efficient)

I released a version a while ago with a crude multi screen support. Take a look: https://github.com/mlaily/NegativeScreen/tree/custom_multi_monitor_support

You can download it here: http://arcanesanctum.net/other/NegativeScreen-custom-multi-monitor.exe

**Comment by HerelAdrastel** [comment]
Thanks ! That was really useful ;)
