### ISSUE TITLE
Is it possible to develop NegativeScreen for Gnome and Wayland (linux, Debian)?

### ISSUE THREAD

**Issue by joh4nd** [mlaily/NegativeScreen#30]
If any of you are into Linux, would you consider making an application / some software that does for the user what NegativeScreen does for the user on MS Windows? When I write 'for the user' I intend to imply that the software is going to do something different, but for the user, the change in the colors seen on the screen will be like the changes in the colors on MS Windows using NegativeScreen.

Ohh the irony of shifting from Windows to Linux expecting such software to exist :-) [I can't find it and asked in the community](https://unix.stackexchange.com/q/743252/530603). Although there is also [wl-gammarelay-rs](https://github.com/MaxVerevkin/wl-gammarelay-rs) that may work on [Wayland](https://github.com/swaywm/sway/issues/6577) this does not work on the [Gnome dekstop](https://gitlab.gnome.org/GNOME/mutter/-/issues/1635).

**Comment by mlaily** [comment]
Sorry to disappoint, but NegativeScreen is very dependent of the Windows APIs, so it's very unlikely to be ported to another OS as-is.

I guess the color matrices definitions could probably be reused by an alternative implementation, but I don't know the Linux ecosystem well enough to recommend anything.

I'm going to close this issue since if if another implementation is ever developed for another OS, it probably won't be by me or in this repository...

**Comment by joh4nd** [comment]
cheers

**Comment by mlaily** [comment]
Totally forgot about it until now, but you are not the first to ask this kind of question, and I remembered some people managed to reuse the NegativeScreen matrices on ubuntu with `compton` or `compiz`: https://gitlab.com/vn971/linux-color-inversion / https://github.com/vn971/linux-color-inversion

This was a few years ago already, so the situation may be different now, but I thought I'd mention it anyway...

**Comment by joh4nd** [comment]
Thanks a lot! Sadly, it  does not support Wayland which comes with Debian.

On my SE question I got suggested to using theme change as a way to darken everything. This works to a wide extent. But it is not learly as efficient and smooth as NegativeScreen on MS windows.
