### ISSUE TITLE
Toggle between two background images synced with changing color profiles

### ISSUE THREAD

**Issue by tysonflint** [mlaily/NegativeScreen#7]
I normally have a dark themed background image when my colors are not toggled.  When I toggle to a dark color scheme, my background image inverts and becomes bright.  It would be a nice enhancement to have the option to have NegativeScreen change the background image to a different custom background image when enabled, and revert the background image to the default when toggled back off.  

If we wanted to get even fancier, we could even have another option to read the default background wallpaper image, calculate it's negative value for the color scheme being applied, then write that image to a temp folder, change to the temp image, and toggle to the selected color profile, which would display the negative of the negative background image, hopefully giving the appearance of an unchanged background image.  This would result in only your icons, start bar, and application windows having their colors altered rather than the wallpaper too.  I've got 6 monitors, so performance could be an issue unless those temp files (one per color profile) are generated up front.

**Comment by mlaily** [comment]
I'm not a fan of programs messing with my settings.

In this particular case, there are a lot of issues that could arise: what about desktop image synchronization for example? (default when login with a microsoft account), or what if the application crashes, or the power goes down and the PC shuts down? It would not be possible to properly restore the old background.

There is another technical issue: it's not always possible to get the exact image back after inverting it twice, because some color information is lost. Try to take a screenshot of your background, save it, then invert it a second time to see what I mean.

Anyway, I don't know about you, but I don't see my background often, so this does not seem that important. This would be "icing on the cake" kind of feature if it could be done properly...
